### ISSUE TITLE
최소 직사각형

### ISSUE THREAD

**Issue by jinah92** [COMA-coding-master/COMA-coding-master.github.io#6]
https://coma-coding-master.github.io/weekly-challenge/%EC%B5%9C%EC%86%8C%EC%A7%81%EC%82%AC%EA%B0%81%ED%98%95/#post-comment 

 최소 직사각형, weekly-challenge, python,

**Comment by jinah92** [comment]
hello world!

**Comment by Ysp9714** [comment]
hello
